export const CONFIG = {
  APP_NAME: 'Geek',
  MIN_TRUST_FOR_POST: 20,
  MIN_TRUST_FOR_BBS: 10,
  MAX_TAGS_PER_POST: 5,
  MAX_MEDIA_PER_POST: 4,
  MAX_CAPTION_LENGTH: 2000,
  MAX_BBS_REPLY_LENGTH: 1000,
} as const;
